package: community.lazycat.app.bookorbit
version: 3.1.0
name: BookOrbit
description: "BookOrbit: Your Reading Space"
min_os_version: 1.5.0
author: bookorbit
license: AGPL-3.0-only
homepage: https://github.com/bookorbit/bookorbit
permissions:
  required:
    - net.internet
    - document.private
locales:
  zh:
    name: "BookOrbit"
    description: "属于你的阅读空间"
  en:
    name: "BookOrbit"
    description: "BookOrbit: Your Reading Space"
